name: Feature Request
description: Suggest an idea for this project
labels: ['kind/enhancement', 'status/need-triage']
body:
  - type: markdown
    attributes:
      value: |
        > [!IMPORTANT]  
        > Thanks for taking the time to suggest an enhancement!
        >
        > Please search **[existing issues](https://github.com/google-gemini/gemini-cli-action/issues)** to see if a similar feature has already been requested.

  - type: textarea
    id: feature
    attributes:
      label: 
      description: 
    validations:
      required: 

  - type: textarea
    id: rationale
    attributes:
      label: 
      description:
    validations:
      required: 

  - type: textarea
    id: additional-context
    attributes:
      label: 
      description: 
